
language: objective-c
osx_image: xcode8

before_install:
  - export LANG=en_US.UTF-8
install:
  - gem install cocoapods --no-document
  - gem install xcpretty --no-document
  - pod repo update
  - pod install
  - cd Project && pod install

script:
  - rake travis
env:
  # Travis hardware is too slow to run the iOS tests as the build exceeds the
  # allowed time of 50 minutes. Rely on Jenkins coverage for iOS for now.
  #- PLATFORM=iOS
  - PLATFORM=OSX
